config/routes.rb
Rails.application.routes.draw do
  get 'procedures/new'
  get 'procedures/edit'
  get 'materials/new'
  get 'materials/edit'
  get 'details/new'
  devise_for :users

  root 'homes#top'
  get 'homes/about'

  resources :users, only: [:show ,:edit ,:update ,:destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
   collection do
     get 'leave'
   end
   member do
     get 'recipes' => 'users#recipes', as:'recipe_indedx'
     get 'favorite' => 'favorites#favorite', as:'favorite'
   end
   end

   resources :recipes do
    member do
      get 'category_all_index'
      get 'category_index'
    end

    collection do
      get 'search' => 'recipes#search', as: 'search'
    end

    resources :materials, only:[:create,:new,:edit ,:update,:destroy]
    resources :procedures, only:[:create,:new,:edit ,:update,:destroy]
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create,:destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :recipes

	belongs_to :parent_category

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :recipe

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord

	belongs_to :recipe

	attachment :image

	validates :recipe_id, presence: true
	validates :name, presence: true, length: {maximum: 20, minimum: 2
	}
	validates :quantity, presence: true, length: {maximum: 5, minimum: 1
	}

	def self.ransackable_attributes(auth_object = nil)
    %w(name)
	end

end

app/models/parent_category.rb
class ParentCategory < ApplicationRecord
	has_many :category
	has_many :recipes, through: :category
end

app/models/procedure.rb
class Procedure < ApplicationRecord
	belongs_to :recipe

	attachment :image

    validates :recipe_id, presence: true
	validates :explanation, presence: true, length: {maximum: 100, minimum: 2
	}

	def self.ransackable_attributes(auth_object = nil)
    %w(name)
	end
end

app/models/recipe.rb
class Recipe < ApplicationRecord

	belongs_to :category
	belongs_to :user

	has_many :materials, dependent: :destroy
	has_many :procedures, dependent: :destroy

	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorite, source: :user
	    def favorited_by?(user)
        	favorites.where(user_id: user.id).exists?
        end

    has_many :comments, dependent: :destroy
 	has_many :tags, dependent: :destroy

	attachment :image

	validates :title, presence: true, length: {maximum: 12, minimum: 2}
	validates :outline, presence: true, length: {maximum: 150, minimum: 5}
	validates :category_id, presence: true

  	def self.ransackable_attributes(auth_object = nil)
    %w(title outline)
	end

	def if_is_closed
		koukai = "公開"
		hikoukai = "非公開"
		if true == is_closed
			hikoukai
		else
			koukai
		end
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  attachment :image

  has_many :recipes, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe

  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
	@category_list = ParentCategory.all
	@favorite_rank = Recipe.find(Favorite.group(:recipe_id).order('count(recipe_id) desc').limit(3).pluck(:recipe_id))
  	@new_recipe = Recipe.where(is_closed: false).order(created_at: :desc).limit(6)
  end

  def about
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!,except:[:search,:index,:category_all_index,:category_index,:show]
  before_action :category_list, only: [:search, :index, :category_all_index,:category_index, :show]
  before_action :set_recipe, only: [:show, :edit, :update]


  def new
    @recipe = Recipe.new
    @material = @recipe.materials.build
    @procedure = @recipe.procedures.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      tags = Vision.get_image_data(@recipe.image)
      tags.each do |tag|
       @recipe.tags.create(name: tag)
      end
      redirect_to new_recipe_material_path(@recipe)
    else
     render :new
    end
  end

  def search
    #ransackの検索で使用する変数は、application_controllerのset_searchで定義済み
  end

  def index
    @recipes = @q.result(distinct: true).page(params[:page]).reverse_order
  end

  def category_all_index
    @parent_category = ParentCategory.find(params[:id])
    @recipes = @parent_category.recipes.where(is_closed: false).page(params[:page]).reverse_order
  end

  def category_index
    @category = Category.find(params[:id])
    @recipes = @category.recipes.where(is_closed: false).page(params[:page]).reverse_order
  end

  def show
    @category = @recipe.category
    @parent_category = @category.parent_category
    @materials = @recipe.materials
    @procedures = @recipe.procedures
    @comments = @recipe.comments
    @comment = Comment.new
  end

  def edit
    @materials = @recipe.materials
    @procedures = @recipe.procedures
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      @materials = @recipe.materials
      @procedures = @recipe.procedures
      render :edit
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path
  end

    private
      def category_list #ページの左側のカテゴリーリスト
        @category_list = ParentCategory.all
      end

      def set_recipe
        @recipe = Recipe.find(params[:id])
      end

      def recipe_params
        params.require(:recipe).permit(
          :title,:outline, :image, :category_id, :is_closed)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def recipes
  	@user = User.find(params[:id])
  	@recipes = Recipe.where(user_id: @user.id)
  end

  def show
  	@user = User.find(params[:id])
  	@recipes = Recipe.where(user_id: @user.id)
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def leave
  	@user = current_user
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_path
  end


	private
	  def user_params
	    params.require(:user).permit(:name,:image, :introduction)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipes/_category.html.erb
<div class="col-xs-3">
	<div class="side_bar">
		<div class="search_btn">
			<%= link_to 'レシピ詳細検索' ,search_recipes_path ,class: "btn btn-lg btn-block btn-blue" %>
		</div>
		<div class="category_list">
			<table class="table">
				<thead>
					<tr>
						<th>カテゴリー 一覧</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
						<% categories.each do |parent| %>
							<h5><strong><%= link_to category_all_index_recipe_path(parent) do %>
								 <%= parent.name %>　全て
								 <% end %></strong></h5>
								<% parent.category.each do |sub_category| %>
								<h5>　<%= link_to category_index_recipe_path(sub_category) do  %>
										<%=sub_category.name %><% end %></h5>
								<% end %>
							<% end %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/recipes/_recipes_index.html.erb
<div class="recipe_index">
	<% if recipes.present? %>
		<% recipes.each do |recipe| %>
			<div class="recipe_div">
				<%= link_to recipe_path(recipe) do %>
					<%= attachment_image_tag recipe, :image, :fill, 180, 120,format: "jpeg" , fallback: "no_image.jpg", size: "180x120" %><br>
					<%= recipe.title %>			<% end %>
				<p class="favo_heart">
					<span class="glyphicon glyphicon-heart"></span>
					<%= recipe.favorites.count %>
				<% if recipe.is_closed != false%>
				<%= recipe.if_is_closed %><% end %>
				</p>
			</div>
		<% end %>
		<%= paginate recipes, class: "paginate" %>
	<% else %>
		<div class="recipe_no_message" align="center">投稿レシピはありません</div>
	<% end %>
</div>

app/views/recipes/category_all_index.html.erb
<div class="row ">
	<div class="col-xs-12">
		<%= render 'category', categories: @category_list %>
		<div class="col-xs-8">
			カテゴリー：
			<%= @parent_category.name %> 　＞
				<% @parent_category.category.each do |sub_category| %>
				<span><%= link_to category_index_recipe_path(sub_category) do  %>
					<%= sub_category.name %></span>
				<% end %>
				<span>/</span>
			<% end %>
			<article class="recipes_index">
				<div class="row recipes_index_contents">
				<h2><strong><%= @parent_category.name %></strong>の全カテゴリーレシピ一覧</h2>
					<%= render 'recipes_index', recipes: @recipes %>
				</div>
			</article>
		</div>
	</div>
</div>

app/views/recipes/category_index.html.erb
<div class="row ">
	<div class="col-xs-12">
		<%= render 'category', categories: @category_list %>
		<div class="col-xs-8">
			カテゴリー：<%= link_to @category.parent_category.name, category_all_index_recipe_path( @category.parent_category) %> 　＞　<%= @category.name %>
			<article class="recipes_index">
				<div class="row recipes_index_contents">
				<h2><strong><%= @category.name %></strong>のレシピ一覧</h2>
					<%= render 'recipes_index', recipes: @recipes %>
				</div>
			</article>
		</div>
	</div>
</div>

app/views/recipes/edit.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
			<!-- エラーメッセージ -->
			<%= render 'layouts/error', array: @recipe %>
			<!-- エラーメッセージ -->
		<%= form_for(@recipe, url:recipe_path) do |f| %>
		<div class="recipe_new">
			<div class="row recipe_new_margin">
				<div class="col-xs-5">
					<h3>画像</h3>
					<%= attachment_image_tag @recipe, :image,:fill,300,200,fallback: "no_image.jpg", size:'300x200', id: "file-preview" %>
						<%= f.attachment_field :image, class: "btn  item_attachment_field", id: "image_select"%>
						<label for="image_select" class="btn btn-blue item_attachment_field" style="display: block;">画像選択</label>
				</div>
				<div class="col-xs-7">
					<h3>レシピタイトル</h3>
					<%= f.text_field :title, placeholder: "タイトル(必須)", class: "form-control" %>
					<h3>カテゴリー</h3>
					 <%= f.grouped_collection_select(:category_id, ParentCategory.all, :category, :name, :id, :name,{include_blank: '選択してください(必須)'},class: 'form-control')%>
					<h3>概要</h3>
						<%= f.text_area :outline, placeholder: "レシピの紹介文(必須)", rows:'5', class: "form-control" %>
				</div>
			</div>
		</div>
		<div class="action" align="center">
			<%= f.submit "　　レシピの変更を保存する　　" ,class: "btn btn-blue btn-lg" %>
		</div>
		<% end %>
		<div class="recipe_new">
			<div class="row recipe_new_margin">
				<h3>レシピ材料</h3>
				<table class="table">
					<thead>
						<tr>
							<th class="col-xs-2">画像</th>
							<th class="col-xs-3">材料名</th>
							<th class="col-xs-2">数量</th>
							<th class="col-xs-3">メーカー（任意）</th>
							<th colspan="2"></th>
						</tr>
					</thead>
					<tbody>
						<% @materials.each do |material| %>
						<tr>
							<td><%= attachment_image_tag material, :image, format: "jpeg" , fallback: "no_image.jpg", id: "material-image" %></td>
							<td><%= material.name %></td>
							<td><%= material.quantity %></td>
							<td><%= material.maker %></td>
							<td><%= link_to '編集' ,edit_recipe_material_path(@recipe.id, material) %></td>
							<td><%= link_to '削除', recipe_material_path(@recipe.id, material),method: :delete, data: {confirm: "削除してよろしいですか？"} %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
				<div align="center">
					<%= link_to '材料の新規追加',new_recipe_material_path(@recipe), method: :get, data: { confirm:  'レシピの概要の変更を保存しないまま移動をすると入力データが消えてしまいます。移動してもよろしいですか？' },class: "btn btn-blue btn-lg" %>
				</div>
			</div>
		</div>
		<div class="recipe_new">
			<div class="row recipe_new_margin">
			<h3>レシピ手順</h3>
				<table class="table">
					<thead>
						<tr>
							<th class="col-xs-1"></th>
							<th class="col-xs-2">画像</th>
					        <th class="col-xs-7">手順説明</th>
					        <th></th>
					    </tr>
					</thead>
					<% @procedures.each.with_index(1) do |procedure, idx| %>
					<tbody>
						<tr>
							<td><%= idx %></td>
							<td><%= attachment_image_tag procedure, :image, format: "jpeg" , fallback: "no_image.jpg", id: "procedure-image" %></td>
							<td><%= procedure.explanation %></td>
							<td><%= link_to '編集' ,edit_recipe_procedure_path(@recipe.id, procedure) %></td>
							<td><%= link_to '削除', recipe_procedure_path(@recipe.id, procedure),method: :delete, data: {confirm: "削除してよろしいですか？"} %></td>
						</tr>
					</tbody>
					<% end %>
				</table>
				<div align="center">
					<%= link_to '手順の新規追加',new_recipe_procedure_path(@recipe), method: :get, data: { confirm: 'レシピの概要の変更を保存しないまま移動をすると入力データが消えてしまいます。移動してもよろしいですか？' },class: "btn btn-blue btn-lg"%>
				</div>
			</div>
		</div>
		<div align="right">
				<%= link_to 'このレシピを削除する', recipe_path(@recipe),method: :delete, data: { confirm: 'レシピを削除してもよろしいですか？（材料、手順すべてのデータが削除されます。）' }, class: "btn btn-red"%>
		</div>
	</div>
</div>


<!-- 画像選択した際に、選択した画像を表示させるjavascript -->
<script>
	document.getElementById('image_select').addEventListener('change', function (e) {
    // 1枚だけ表示する
    var file = e.target.files[0];

    // ファイルのブラウザ上でのURLを取得する
    var blobUrl = window.URL.createObjectURL(file);

    // img要素に表示
    var img = document.getElementById('file-preview');
    img.src = blobUrl;
});
</script>

app/views/recipes/index.html.erb
<div class="row">
	<div class="col-xs-12">
		<%= render 'category', categories: @category_list %>
		<div class="col-xs-8">
			<article class="recipes_index">
				<div class="row recipes_index_contents">
				<h2>レシピ一覧</h2>
					<%= render 'recipes_index', recipes: @recipes %>
				</div>
			</article>
		</div>
	</div>
</div>

app/views/recipes/new.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<h4>STEP：1　レシピのタイトルと概要を作成してください。</h4>
		<!-- エラーメッセージ -->
		<%= render 'layouts/error', array: @recipe %>
		<!-- エラーメッセージ -->
		<%= form_for(@recipe) do |f| %>
		<div class="recipe_new">
			<div class="row recipe_new_margin">
				<div class="col-xs-5">
					<h3>画像</h3>
						<div class="recipe_new_image">
							<%= attachment_image_tag @recipe, :image,:fill, 300,200,fallback: "no_image.jpg", size:'300x200', id: "file-preview" %>
							<%= f.attachment_field :image, class: "btn btn-blue achment_field", id: "image_select"%>
							<label for="image_select" class="btn btn-blue item_attachment_field" style="display: block;">画像選択</label>
						</div>
				</div>
				<div class="col-xs-7">
					<h3>レシピタイトル</h3>
					<%= f.text_field :title, placeholder: "タイトル(必須)", class: "form-control" %>
					<h3>カテゴリー</h3>
					 <%= f.grouped_collection_select(:category_id, ParentCategory.all, :category, :name, :id, :name,{include_blank: '選択してください(必須)'},class: 'form-control' )%>
					<h3>概要</h3>
						<%= f.text_area :outline, placeholder: "レシピの紹介文(必須)", rows:'5', class: "form-control" %>
						<%= f.hidden_field :is_closed, :value => true %>
				</div>
			</div>
		</div>
		<div class="row new_btn" align="center">
			<span><%= f.submit "STEP：２　材料の登録へ進む" ,class: "btn btn-blue btn-lg" %></span>
			<p>※この段階では非公開です</p>
		</div>
		<% end %>
	</div>
</div>

<!-- 画像選択した際に、選択した画像を表示させるjavascript -->
<script>
	document.getElementById('image_select').addEventListener('change', function (e) {
    // 1枚だけ表示する
    var file = e.target.files[0];

    // ファイルのブラウザ上でのURLを取得する
    var blobUrl = window.URL.createObjectURL(file);

    // img要素に表示
    var img = document.getElementById('file-preview');
    img.src = blobUrl;
});
</script>

app/views/recipes/search.html.erb
<div class="conteiner">
	<div class="row">
		<div class="col-xs-11 col-xs-offset-1">
			<%= render 'category', categories: @category_list %>
			<div class="col-xs-8">
				<article class="search_table">
				<h2>レシピ　絞り込み検索</h2>
					<%= search_form_for @q do |f| %>
					<div class="form-group search_form">
						<!-- 　 検索対象のカラムを:hoge_contで示す。itemnameだったらitemname_cont -->
						<table class="table">
							<tbody>
								<tr>
									<th class="col-xs-4"><%= f.label :category_id_eq, 'カテゴリー' %></th>
									<td><%= f.grouped_collection_select(:category_id_eq, ParentCategory.all, :category, :name, :id, :name,{include_blank: '選択してください'},class: 'form-control' )%></td>
								</tr>
								<tr>
									<th class="col-xs-4"><%= f.label :title_or_outline_cont, "タイトル・説明キーワード" %></th>
									<td><%= f.search_field :title_or_outline_cont, placeholder: '検索ワードを入力', class: "form-control" %></td>
								</tr>
								<tr>
									<th class="col-xs-4"><%= f.label :materials_name_cont, "材料キーワード" %></th>
									<td><%= f.search_field :materials_name_cont, placeholder: '検索ワードを入力', class: "form-control" %></td>
								</tr>
								<tr>
									<td align="center" colspan="2" ><%= f.submit "　　検索　　",class: "btn btn-blue btn-lg" %></td>
								</tr>
							</tbody>
						</table>
					</div>
					<% end %>
				</article>
				<div align="right" colspan="2" ><%= link_to "レシピ一覧へ",recipes_path ,class: "btn btn-blue" %>
		</div>
	</div>
</div>

app/views/recipes/show.html.erb
<div class="row">
	<div class="col-xs-12">
		<%= render 'category', categories: @category_list %>
		<div class="col-xs-9">
			<div class="row">
				カテゴリー：<%= link_to @parent_category.name, category_all_index_recipe_path(@parent_category) %>
					 ＞ <%= link_to @category.name, category_index_recipe_path(@category) %>
				<div id="favorite_buttons_<%= @recipe.id %>" align="right">
					<%= render partial: 'favorites/favorite_btn', locals: { recipe: @recipe} %>
				</div>
			</div>
			<div class="recipe_show">
				<div class="recipe_show_margin">
					<h2>
						<%= @recipe.title %>
						<span class="post_user">
							<p>
								投稿者：<%= link_to @recipe.user.name, user_path(@recipe.user.id)%>
								<% if @recipe.user == current_user %>
									<%= link_to "編集する", edit_recipe_path(@recipe),class: "btn btn-red btn-sm" %>
									<%= @recipe.if_is_closed %>
									<%= form_for(@recipe, url:recipe_path) do |f| %>
									<% if @recipe.is_closed == false %>
										<%= f.hidden_field :is_closed,:value =>'true'%>
										<%= f.submit '非公開にする',class: "btn btn-blue btn-sm" %>
									<% else %>
										<%= f.hidden_field :is_closed,:value => 'false' %>
										<%= f.submit '公開する',class: "btn btn-blue btn-sm" %>
										<% end %>
									<% end %>
								<% end %>
							</p>
						</span>
					</h2>
				</div>
				<div class="row recipe_show_margin">
					<p>
						投稿時間：<%= @recipe.created_at.to_s(:datetime_jp) %>
					</p>
					<div class="col-xs-5 recipe_show_image">
						<%= attachment_image_tag @recipe, :image, :fill, 300,200,format: "jpeg" , fallback: "no_image.jpg", size:'300x200' %>
					</div>
					<div class="col-xs-7">
						<div class="outline"><%= @recipe.outline %></div>
					<div>
		              <% @recipe.tags.each do |tag| %>
		                <span class="label label-primary"><%= tag.name %></span>
		              <% end %>
            		</div>

						<h3>レシピ材料</h3>
						<table class="table material_table">
							<% @materials.each do |material| %>
							<tbody>
								<tr>
									<td><%= attachment_image_tag material, :image, format: "jpeg" , fallback: "no_image.jpg", id: "material-image"  %></td>
									<td><%= material.name %></td>
									<td><%= material.quantity %></td>
									<td><%= material.maker %></td>
								</tr>
							</tbody>
							<% end %>
						</table>
					</div>
				</div>
			<div class="row recipe_show_margin">
				<h3>レシピ手順</h3>
				<table class="table procedure_table">
					<% @procedures.each.with_index(1) do |procedure, idx| %>
					<tbody>
						<tr>
							<td><%= idx %></td>
							<td class="col-xs-2" align="center"><%= attachment_image_tag procedure, :image, format: "jpeg" , fallback: "no_image.jpg", id: "procedure-image" %></td>
							<td class="col-xs-10"><%= procedure.explanation %></td>
						</tr>
					</tbody>
					<% end %>
				</table>
			</div>
		</div>
		<div class="conteiner comment_show">
			<div class="row recipe_comment_margin">
				<div class="comment">
					<h3>コメント</h3>
					<div id="comments_area">
						<%= render partial:'comments/comment_index',locals: { comments: @comments, recipe: @recipe} %>
						<% if user_signed_in? %>
							<%= render partial: 'comments/form', locals: { comment: @comment, recipe: @recipe } %>
						<% else %>
							<div class="not_login" align="center">
								<%= link_to '会員ログイン', new_user_session_path %>　をするとコメントができるようになります。
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>