config/routes.rb
Rails.application.routes.draw do
  get 'procedures/new'
  get 'procedures/edit'
  get 'materials/new'
  get 'materials/edit'
  get 'details/new'
  devise_for :users

  root 'homes#top'
  get 'homes/about'

  resources :users, only: [:show ,:edit ,:update ,:destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
   collection do
     get 'leave'
   end
   member do
     get 'recipes' => 'users#recipes', as:'recipe_indedx'
     get 'favorite' => 'favorites#favorite', as:'favorite'
   end
   end

   resources :recipes do
    member do
      get 'category_all_index'
      get 'category_index'
    end

    collection do
      get 'search' => 'recipes#search', as: 'search'
    end

    resources :materials, only:[:create,:new,:edit ,:update,:destroy]
    resources :procedures, only:[:create,:new,:edit ,:update,:destroy]
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create,:destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :recipes

	belongs_to :parent_category

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :recipe

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord

	belongs_to :recipe

	attachment :image

	validates :recipe_id, presence: true
	validates :name, presence: true, length: {maximum: 20, minimum: 2
	}
	validates :quantity, presence: true, length: {maximum: 5, minimum: 1
	}

	def self.ransackable_attributes(auth_object = nil)
    %w(name)
	end

end

app/models/parent_category.rb
class ParentCategory < ApplicationRecord
	has_many :category
	has_many :recipes, through: :category
end

app/models/procedure.rb
class Procedure < ApplicationRecord
	belongs_to :recipe

	attachment :image

    validates :recipe_id, presence: true
	validates :explanation, presence: true, length: {maximum: 100, minimum: 2
	}

	def self.ransackable_attributes(auth_object = nil)
    %w(name)
	end
end

app/models/recipe.rb
class Recipe < ApplicationRecord

	belongs_to :category
	belongs_to :user

	has_many :materials, dependent: :destroy
	has_many :procedures, dependent: :destroy

	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorite, source: :user
	    def favorited_by?(user)
        	favorites.where(user_id: user.id).exists?
        end

    has_many :comments, dependent: :destroy
 	has_many :tags, dependent: :destroy

	attachment :image

	validates :title, presence: true, length: {maximum: 12, minimum: 2}
	validates :outline, presence: true, length: {maximum: 150, minimum: 5}
	validates :category_id, presence: true

  	def self.ransackable_attributes(auth_object = nil)
    %w(title outline)
	end

	def if_is_closed
		koukai = "公開"
		hikoukai = "非公開"
		if true == is_closed
			hikoukai
		else
			koukai
		end
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  attachment :image

  has_many :recipes, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe

  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
	@category_list = ParentCategory.all
	@favorite_rank = Recipe.find(Favorite.group(:recipe_id).order('count(recipe_id) desc').limit(3).pluck(:recipe_id))
  	@new_recipe = Recipe.where(is_closed: false).order(created_at: :desc).limit(6)
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def recipes
  	@user = User.find(params[:id])
  	@recipes = Recipe.where(user_id: @user.id)
  end

  def show
  	@user = User.find(params[:id])
  	@recipes = Recipe.where(user_id: @user.id)
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def leave
  	@user = current_user
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_path
  end


	private
	  def user_params
	    params.require(:user).permit(:name,:image, :introduction)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_profile.html.erb
<div class="row">
	<table class="table">
		<thead>
			<tr><th>ユーザー情報</th></tr>
		</thead>
		<tbody>
			<tr>
				<td colspan="2" align="center"><%= attachment_image_tag user, :image, :fill,200,200, format: 'jpeg', class: "profile-thumb", fallback: "no_image.jpg", size:'200x200' %>
					<%= render 'relationships/follow_btn', user: @user %>
				</td>
			</tr>
			<tr>
				<th>ニックネーム</th>
			</tr>
			<tr>
				<td class="name" align="center"><%= link_to user_path(user) do %><strong>
					<%= user.name %></strong><% end %></td>
			</tr>
			<tr>
				<th>自己紹介</th>
			</tr>
			<tr>
				<td colspan="2"><%= user.introduction %></td>
			</tr>
			<tr>
		<% if current_page?(root_path) %>
			<td class="home_btn"><%= link_to "いいねしたレシピ一覧", favorite_user_path(user),class: "btn btn-blue btn-block" %></td>
			<td class="home_btn"><%= link_to "ユーザのレシピ一覧", recipe_indedx_user_path(user),class: "btn btn-blue btn-block" %></td>
		<% elsif current_page?(controller: 'users', action: 'recipes') %>
			<td class="home_btn"><%= link_to "いいねしたレシピ一覧", favorite_user_path(user),class: "btn btn-blue btn-block" %></td>
		<% elsif current_page?(controller: 'favorites', action: 'favorite') %>
			<td class="home_btn"><%= link_to "ユーザのレシピ一覧", recipe_indedx_user_path(user),class: "btn btn-blue btn-block" %></td>
		<% end %>
			</tr>
		</tbody>
	</table>
</div>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<h2>ユーザー情報変更</h2>
			<!-- エラーメッセージ -->
			<%= render 'layouts/error', array: @user %>
			<!-- エラーメッセージ -->
		<%= form_for @user, url: user_path do |f| %>
		<div class="user_profile">
			<div class="row user_profile_margin">
				<div class="col-xs-5">
					<h3>プロフィール画像</h3>
					<div align="center">
						<%= attachment_image_tag @recipe, :image, fallback: "no_image.jpg", size:'200x200', id: "file-preview" %>
						<%= f.attachment_field :image, class: "btn btn-blue item_attachment_field", id: "image_select"%>
						<label for="image_select" class="btn btn-blue item_attachment_field" style="display: block;">画像選択</label>
					</div>
				</div>
				<div class="col-xs-7">
					<h3>ニックネーム</h3>
					<%= f.text_field :name, class: 'form-control' %>
					<h3>自己紹介文</h3>
					<%= f.text_area :introduction, rows:'4' ,class: 'form-control' %>
				</div>
			</div>
		</div>
		<div class="action" align="center">
				<%= f.submit "　　ユーザー情報を変更する　　" ,class: "btn btn-blue btn-lg" %>
		</div>
		<div class="action" align="right">
				<%= link_to '退会する',leave_users_path ,class: "btn btn-red" %>
		</div>
		<% end %>
	</div>
</div>

<!-- 画像選択した際に、選択した画像を表示させるjavascript -->
<script>
	document.getElementById('image_select').addEventListener('change', function (e) {
    // 1枚だけ表示する
    var file = e.target.files[0];

    // ファイルのブラウザ上でのURLを取得する
    var blobUrl = window.URL.createObjectURL(file);

    // img要素に表示
    var img = document.getElementById('file-preview');
    img.src = blobUrl;
});
</script>

app/views/users/leave.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="leave-confirm-message">
				<h2 align="center">本当に退会しますか？</h2>
				<h3 align="center">退会すると、これまでに投稿したレシピが削除されます。<br>また、いいねをしたレシピの一覧もできなくなります。<br>退会する場合は、「退会する」をクリックしてください。</h3>

				<div class="col-xs-6 col-xs-offset-3 leave-btn">
					<div class="col-xs-6">
						<%= link_to '退会しない',user_path(current_user), class: "btn btn-lg btn-blue" %>
					</div>
					<div class="col-xs-6">
						<%= link_to '退会する', user_registration_path,method: :delete, class: "btn btn-lg btn-red" %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/recipes.html.erb
<div class="conteiner">
	<div class="row">
		<div class="col-xs-3 user_profile">
			<%= render 'user_profile', user: @user %>
		</div>
		<div class="col-xs-8 recipes_index">
			<h2><%= @user.name %>の投稿レシピ</h2>
			<p>全<strong><%= @recipes.count %></strong>件</p>
			<%= render 'recipes/recipes_index', recipes: @recipes %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="conteiner">
	<div class="row">
		<div class="col-xs-12">
			<div class="col-xs-8">
				<div class="row">
					<div class="user_profile">
						<table class="table">
							<thead>
								<tr>
									<th colspan="3">ユーザー情報
									</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td colspan="3" align="center">
									<%= attachment_image_tag @user, :image, :fill, 200, 200, format: 'jpeg', class: "profile-thumb", fallback: "no_image.jpg", size:'200x200' %>
									<%= render 'relationships/follow_btn', user: @user %>
									</td>
								</tr>
								<tr>
									<th colspan="3">ニックネーム</th>
								</tr>
								<tr>
									<td colspan="3" align="center"><strong><%= @user.name %></strong></td>
								</tr>
								<tr>
									<th colspan="3">自己紹介</th>
								</tr>
								<tr>
									<td colspan="3" align="center"><%= @user.introduction %></td>
								</tr>
								<tr>
									<th class="col-xs-5">フォロー</th>
									<td class="col-xs-2" align="center"><%= @user.follower.count%></td>
									<td class="col-xs-5"><%= link_to "フォローの一覧",  user_follows_path(@user),class: "btn btn-blue" %></td>
								</tr>
								<tr>
									<th class="col-xs-5">フォロワー</th>
									<td class="col-xs-2" align="center"><%= @user.followed.count %></td>
									<td class="col-xs-5"><%= link_to "フォロワーの一覧",  user_followers_path(@user),class: "btn btn-blue" %></td>
								</tr>
								<tr>
									<th class="col-xs-5">投稿したレシピ数</th>
									<td class="col-xs-2" align="center"><%= @recipes.count %></td>
									<td class="col-xs-5"><%= link_to "投稿レシピ一覧へ", recipe_indedx_user_path(@user),class: "btn btn-blue" %></td>
								</tr>
								<tr>
									<th class="col-xs-5">いいねしたレシピ数</th>
									<td class="col-xs-2" align="center"><%= @user.favorites.count %></td>
									<td>
									<%= link_to "いいねしたレシピ一覧へ", favorite_user_path(@user),class: "btn btn-blue" %></td>
								</tr>
							</tbody>
						</table>
						<div class="user_edit_btn" align="center">
						<% if current_user == @user %>
							<%= link_to "編集する", edit_user_path(@user),class: "btn btn-red btn-lg" %>
						<% end %>
						</div>
					</div>

					<div>
						<%= link_to '戻る', 'javascript:history.back()',class: "btn btn-blue" %>
					</div>
				</div>
			</div>
			<div class="col-xs-4 recipes_index">
				<h2 align="center">
					<% if current_user != @user %>
						<%= @user.name %>の投稿レシピ
					<% else %>
						あなたの投稿レシピ
					<% end %>
				</h2>
				<table class="table">
					<% @recipes.last(4).each do |recipe| %>
					<tbody>
						<tr>
							<td align="center">
								<%= link_to (recipe) do %>
								<%= attachment_image_tag recipe, :image, :fill, 200, 150,format: "jpeg" , fallback: "no_image.jpg", size:'200x150' %><br>
								<% end %>
								<%= link_to recipe.title, recipe_path(recipe), class: "recipe_link" %>
								<%= recipe.if_is_closed %>
							</td>
						</tr>
					</tbody>
					<% end %>
				</table>
					<% if @recipes.present? %>
						<p align="right"><%= link_to ">>ユーザのレシピをもっと見る", recipe_indedx_user_path(@user) %></p>
					<% else %>
						<p align="right">ユーザーの投稿レシピはありません</p>
					<% end %>
			</div>
		</div>
	</div>
</div>