config/routes.rb
Rails.application.routes.draw do
  get 'procedures/new'
  get 'procedures/edit'
  get 'materials/new'
  get 'materials/edit'
  get 'details/new'
  devise_for :users

  root 'homes#top'
  get 'homes/about'

  resources :users, only: [:show ,:edit ,:update ,:destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
   collection do
     get 'leave'
   end
   member do
     get 'recipes' => 'users#recipes', as:'recipe_indedx'
     get 'favorite' => 'favorites#favorite', as:'favorite'
   end
   end

   resources :recipes do
    member do
      get 'category_all_index'
      get 'category_index'
    end

    collection do
      get 'search' => 'recipes#search', as: 'search'
    end

    resources :materials, only:[:create,:new,:edit ,:update,:destroy]
    resources :procedures, only:[:create,:new,:edit ,:update,:destroy]
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create,:destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :recipes

	belongs_to :parent_category

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :recipe

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord

	belongs_to :recipe

	attachment :image

	validates :recipe_id, presence: true
	validates :name, presence: true, length: {maximum: 20, minimum: 2
	}
	validates :quantity, presence: true, length: {maximum: 5, minimum: 1
	}

	def self.ransackable_attributes(auth_object = nil)
    %w(name)
	end

end

app/models/parent_category.rb
class ParentCategory < ApplicationRecord
	has_many :category
	has_many :recipes, through: :category
end

app/models/procedure.rb
class Procedure < ApplicationRecord
	belongs_to :recipe

	attachment :image

    validates :recipe_id, presence: true
	validates :explanation, presence: true, length: {maximum: 100, minimum: 2
	}

	def self.ransackable_attributes(auth_object = nil)
    %w(name)
	end
end

app/models/recipe.rb
class Recipe < ApplicationRecord

	belongs_to :category
	belongs_to :user

	has_many :materials, dependent: :destroy
	has_many :procedures, dependent: :destroy

	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorite, source: :user
	    def favorited_by?(user)
        	favorites.where(user_id: user.id).exists?
        end

    has_many :comments, dependent: :destroy
 	has_many :tags, dependent: :destroy

	attachment :image

	validates :title, presence: true, length: {maximum: 12, minimum: 2}
	validates :outline, presence: true, length: {maximum: 150, minimum: 5}
	validates :category_id, presence: true

  	def self.ransackable_attributes(auth_object = nil)
    %w(title outline)
	end

	def if_is_closed
		koukai = "公開"
		hikoukai = "非公開"
		if true == is_closed
			hikoukai
		else
			koukai
		end
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  attachment :image

  has_many :recipes, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe

  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
	@category_list = ParentCategory.all
	@favorite_rank = Recipe.find(Favorite.group(:recipe_id).order('count(recipe_id) desc').limit(3).pluck(:recipe_id))
  	@new_recipe = Recipe.where(is_closed: false).order(created_at: :desc).limit(6)
  end

  def about
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :authenticate_user!
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @materials = @recipe.materials
    @procedures = @recipe.procedures

    @procedure = Procedure.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])

    @procedure = Procedure.new(procedure_params)
    @procedure.recipe_id = @recipe.id
    if @procedure.save
        redirect_to new_recipe_procedure_path(@recipe)
    else
      @recipe = Recipe.find(params[:recipe_id])
      @materials = @recipe.materials
      @procedures = @recipe.procedures
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @procedure = Procedure.find(params[:id])
  end

  def update
    @procedure = Procedure.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
    if @procedure.update(procedure_params)
      redirect_to new_recipe_procedure_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    procedure = Procedure.find(params[:id])
    procedure.destroy
    redirect_to request.referer
  end

  private
  def procedure_params
     params.require(:procedure).permit(:recipe_id,:image, :explanation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def recipes
  	@user = User.find(params[:id])
  	@recipes = Recipe.where(user_id: @user.id)
  end

  def show
  	@user = User.find(params[:id])
  	@recipes = Recipe.where(user_id: @user.id)
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def leave
  	@user = current_user
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_path
  end


	private
	  def user_params
	    params.require(:user).permit(:name,:image, :introduction)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/procedures/edit.html.erb
<div class="col-xs-10 col-xs-offset-1">
	<%= form_for [@recipe, @procedure] do |f| %>
	<div class="procedure_new">
		<div class="procedure_new_margin">
			<h2>手順変更</h2>
			<!-- エラーメッセージ -->
			<%= render 'layouts/error', array: @procedure %>
			<!-- エラーメッセージ -->
			<table class="table">
				<thead>
					<tr>
						<th class="col-xs-4">画像</th>
				        <th class="col-xs-7">手順説明</th>
				    </tr>
				</thead>
				<tbody>
				    <tr>
				    	<td align="center"><%= attachment_image_tag @procedure, :image,:fill,200,150, fallback: "no_image.jpg", size:'200x150', id: "file-preview" %>
						<%= f.attachment_field :image, class: "btn  item_attachment_field", id: "image_select"%>
						<label for="image_select" class="btn btn-blue item_attachment_field" style="display: block;">画像選択</label></td>
				        <td><%= f.text_area :explanation, rows:'5', class: 'form-control' %></td>
				    </tr>
				</tbody>
			</table>
		</div>
	</div>
	<div align="center"><%= f.submit "手順を変更" ,class: "btn btn-blue btn-lg" %></div>
	<% end %>
</div>
<!-- 画像選択した際に、選択した画像を表示させるjavascript -->
<script>
	document.getElementById('image_select').addEventListener('change', function (e) {
    // 1枚だけ表示する
    var file = e.target.files[0];

    // ファイルのブラウザ上でのURLを取得する
    var blobUrl = window.URL.createObjectURL(file);

    // img要素に表示
    var img = document.getElementById('file-preview');
    img.src = blobUrl;
});
</script>

app/views/procedures/new.html.erb
<div class="row">
	<div class="col-xs-11 col-xs-offset-1">
		<h4>STEP：3　手順を登録してください。</h4>
		<div class="row procedure_new">
			<div class="row procedure_new_margin">
				<h2>
					<%= @recipe.title %>
					<span class="is_closed">
						<p>
						<%= @recipe.if_is_closed %>
						</p>
					</span>
				</h2>
				<div class="col-xs-4 " align="center">
					<div class="recipe_new_image">
					<%= attachment_image_tag @recipe, :image, :fill, 300, 200,format: "jpeg" , fallback: "no_image.jpg", size:'300x200' %></div>
				</div>
				<div class="col-xs-8">
					<p align="right"><%= link_to "タイトル・概要を変更する", edit_recipe_path(@recipe),class: "btn btn-blue" %></p>
					<h3><%= @recipe.outline %></h3>

					<h2>レシピ材料</h2>
					<table class="table">
						<thead>
							<tr>
								<th class="col-xs-2">画像</th>
								<th class="col-xs-3">材料名</th>
								<th class="col-xs-2">数量</th>
								<th class="col-xs-3">メーカー（任意）</th>
								<th colspan="2"></th>
							</tr>
						</thead>
						<tbody>
							<% @materials.each do |material| %>
							<tr>
								<td><%= attachment_image_tag material, :image, format: "jpeg" , fallback: "no_image.jpg", id: "material-image" %></td>
								<td><%= material.name %></td>
								<td><%= material.quantity %></td>
								<td><%= material.maker %></td>
								<td><%= link_to '編集' ,edit_recipe_material_path(@recipe.id, material) %></td>
								<td><%= link_to '削除', recipe_material_path(@recipe.id, material),method: :delete, data: {confirm: "削除してよろしいですか？"} %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
					<div align="center">
						<%= link_to '材料の新規追加',new_recipe_material_path(@recipe),class: "btn btn-blue" %>
					</div>
				</div>
			</div>
			<div class="row procedure_new_margin">
				<h2 class="step_title">レシピ手順</h2>
				<!-- エラーメッセージ -->
				<%= render 'layouts/error', array: @procedure %>
				<!-- エラーメッセージ -->
				<table class="table step_table">
					<thead>
						<tr>
							<th></th>
							<th class="col-xs-2">画像</th>
					        <th class="col-xs-7">手順説明</th>
					        <th></th>
					        <th></th>
					    </tr>
					</thead>
					<% @procedures.each.with_index(1) do |procedure, idx| %>
					<tbody>
						<tr>
							<td><%= idx %></td>
							<td align="center"><%= attachment_image_tag procedure, :image, format: "jpeg" , fallback: "no_image.jpg", id: "procedure-image" %></td>
							<td><%= procedure.explanation %></td>
							<td><%= link_to '編集' ,edit_recipe_procedure_path(@recipe.id, procedure) %></td>
							<td><%= link_to '削除', recipe_procedure_path(@recipe.id, procedure),method: :delete, data: {confirm: "削除してよろしいですか？"} %></td>
						</tr>
						<% end %>
				<%= form_for [@recipe, @procedure] do |f| %>
						<tr>
							<td>新規</td>
							<td align="center"><%= attachment_image_tag @procedure, :image, :fill, 100, 80, format: "jpeg" , fallback: "no_image.jpg", size:'100x80', id: "file-preview"%>
								<%= f.attachment_field :image, class: "btn  item_attachment_field", id: "image_select"%>
								<label for="image_select" class="btn btn-red item_attachment_field" style="display: block;">画像</label></td>
					        <td class="col-xs-7"><%= f.text_area :explanation, class: 'form-control' %></td>
					        <td colspan="2"><%= f.submit "手順を追加" ,class: "btn btn-red" %></td>
						</tr>
					</tbody>
				</table>
				<% end %>
	            <div align="center">
	            	<%= link_to '　レシピの内容を保存する　' ,recipe_path(@recipe),method: :get, data: { confirm: '登録した内容のレシピ詳細ページへ移動します。移動してよろしいですか？' },class: "btn btn-blue btn-lg" %>
	            </div>
			</div>
		</div>
	</div>
</div>
<!-- 画像選択した際に、選択した画像を表示させるjavascript -->
<script>
	document.getElementById('image_select').addEventListener('change', function (e) {
    // 1枚だけ表示する
    var file = e.target.files[0];

    // ファイルのブラウザ上でのURLを取得する
    var blobUrl = window.URL.createObjectURL(file);

    // img要素に表示
    var img = document.getElementById('file-preview');
    img.src = blobUrl;
});
</script>