config/routes.rb
Rails.application.routes.draw do
  get 'procedures/new'
  get 'procedures/edit'
  get 'materials/new'
  get 'materials/edit'
  get 'details/new'
  devise_for :users

  root 'homes#top'
  get 'homes/about'

  resources :users, only: [:show ,:edit ,:update ,:destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
   collection do
     get 'leave'
   end
   member do
     get 'recipes' => 'users#recipes', as:'recipe_indedx'
     get 'favorite' => 'favorites#favorite', as:'favorite'
   end
   end

   resources :recipes do
    member do
      get 'category_all_index'
      get 'category_index'
    end

    collection do
      get 'search' => 'recipes#search', as: 'search'
    end

    resources :materials, only:[:create,:new,:edit ,:update,:destroy]
    resources :procedures, only:[:create,:new,:edit ,:update,:destroy]
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create,:destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :recipes

	belongs_to :parent_category

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :recipe

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord

	belongs_to :recipe

	attachment :image

	validates :recipe_id, presence: true
	validates :name, presence: true, length: {maximum: 20, minimum: 2
	}
	validates :quantity, presence: true, length: {maximum: 5, minimum: 1
	}

	def self.ransackable_attributes(auth_object = nil)
    %w(name)
	end

end

app/models/parent_category.rb
class ParentCategory < ApplicationRecord
	has_many :category
	has_many :recipes, through: :category
end

app/models/procedure.rb
class Procedure < ApplicationRecord
	belongs_to :recipe

	attachment :image

    validates :recipe_id, presence: true
	validates :explanation, presence: true, length: {maximum: 100, minimum: 2
	}

	def self.ransackable_attributes(auth_object = nil)
    %w(name)
	end
end

app/models/recipe.rb
class Recipe < ApplicationRecord

	belongs_to :category
	belongs_to :user

	has_many :materials, dependent: :destroy
	has_many :procedures, dependent: :destroy

	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorite, source: :user
	    def favorited_by?(user)
        	favorites.where(user_id: user.id).exists?
        end

    has_many :comments, dependent: :destroy
 	has_many :tags, dependent: :destroy

	attachment :image

	validates :title, presence: true, length: {maximum: 12, minimum: 2}
	validates :outline, presence: true, length: {maximum: 150, minimum: 5}
	validates :category_id, presence: true

  	def self.ransackable_attributes(auth_object = nil)
    %w(title outline)
	end

	def if_is_closed
		koukai = "公開"
		hikoukai = "非公開"
		if true == is_closed
			hikoukai
		else
			koukai
		end
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  attachment :image

  has_many :recipes, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe

  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if array.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
    	<ul>
	        <% array.errors.full_messages.each do |message| %>
	            <li><%= message %></li>
	        <% end %>
    	</ul>
    </div>
<% end %>
<!-- <%#= render 'layouts/erroe', array: "@" %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Found_It!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- header -->
    <header class="navbar navbar-fixed-top" style="background-color: #fafae1;">

    <% if user_signed_in? %>
    <!-- ログイン中のヘッダー -->
      <div class="container">
          <nav class="nav navbar-nav navbar-left">
            <span class="nav navbar-nav"><%= link_to image_tag('logo2.png', class: 'headerlogo'),root_path %></span>
            <span class="navbar-form navbar-nav form" role="search">
              <%= search_form_for @q, url: recipes_path,html: { method: :get } do |f| %>
                <%= f.text_field :title_or_outline_cont, placeholder: 'キーワードで検索', class: "form-control" %>
                <%= f.submit "検索",class: "btn btn-blue" %>
              <% end %>
            </span>
          </nav>
          <nav class="nav navbar-nav navbar-right">
            <ul class="nav navbar-nav">
              <li class="topmenu_btn">
                <span id="new_btn">
                  <%= link_to new_recipe_path do %>
                     <button type="button" class="btn btn-blue btn-circle">＋</button>
                  <% end %>
                </span>
              </li>
              <li role="presentation" class="topmenu dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <%= attachment_image_tag @header_icon_user, :image, :fill,25,25, format: 'jpeg', class: "profile-thumb", fallback: "no_image.jpg", size:'25x25' %>
                  <strong>　<%= current_user.name %></strong>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li role="presentation"><%= link_to 'マイページ',user_path(current_user) %></li>
                  <li role="presentation"><%= link_to '投稿一覧', recipe_indedx_user_path(current_user) %></li>
                  <li role="presentation"><%= link_to "いいね一覧", favorite_user_path(current_user) %></li>
                </ul>
              </li>
              <li class="topmenu"><%= link_to '全レシピ一覧', recipes_path %></li>
              <li class="topmenu"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
            </ul>
        </nav>
      </div>

        <% else %>
    <!-- 未ログインのヘッダー -->
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span class="nav navbar-nav"><%= link_to image_tag('logo2.png', class: 'headerlogo'),root_path %></span>
          <span class="navbar-form navbar-nav" role="search">
            <%= search_form_for @q, url: recipes_path,html: { method: :get } do |f| %>
              <%= f.text_field :title_or_outline_cont, placeholder: 'キーワードで検索', class: "form-control" %>
              <%= f.submit "検索",class: "btn btn-blue" %>
            <% end %>
          </span>
        </nav>
        <nav class="nav navbar-nav navbar-right">
          <ul class="nav navbar-nav">
            <li class="topmenu"><%= link_to 'ABOUT', homes_about_path %></li>
            <li class="topmenu"><%= link_to 'レシピ一覧', recipes_path %></li>
            <li class="topmenu"><%= link_to '会員登録',new_user_registration_path %></li>
            <li class="topmenu"><%= link_to 'ログイン', new_user_session_path %></li>
          </ul>
        </nav>
      </div>

      <% end %>
    </header>
  <!--ヘッダーの記述-->
  <!-- body -->
  <div class="container contents">
      <%= yield %>
  </div>
  <!-- body -->
 <!--フッターの記述-->
    <footer style="background-color: #fafae1;">
      <div class="container col-xs-10 col-xs-offset-1">
        <div class="row">
          <span class="footer-contents"><%= link_to 'About 「Found It!」',homes_about_path %>
          </span>
        </div>
      </div>
    </footer>
  <!-- フッターの記述 -->
  </body>
</html>